name: Delete branch after PR merge

on:
  pull_request:
    types: [closed]  

jobs:
  branchDeletion:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Delete Branch 
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"

          if [[ "$BRANCH_NAME" == "main" || "$BRANCH_NAME" == "master" ]]; then
            echo "Skipping deletion of protected branch: $BRANCH_NAME"
            exit 0
          fi

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote add origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push origin --delete "$BRANCH_NAME"
